****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
ZAL13_COCKPIT_ENDERECO																																
9013																																
750																																
             40																																
%_HEADER																																
ZAL13_COCKPIT_ENDERECO                  9013 9013     20 59192 37  0  0 27123  0G P                              20230626172909																																
%_DESCRIPTION																																
Tela de Cockpit de alteração de endereço																																
%_FIELDS																																
LBMATRICULA	0	CHAR	 13	00	00	00	30	00	  1	  2		  0	  0	  0		  0					  0	  0								Matricula____	                                                                                                                                                                                                                                                        X	
GWA_PA0006-PERNR	N	NUMC	 22	80	00	80	00	00	  1	 16		  0	  0	  0		  0					  0	  0								______________________		
BTNPESQUISAR		CHAR	 23	00	00	00	30	00	  1	 40		  0	  0	  0		 21	P				  0	  0	101							@13@_Pesquisar_________	                                                                                                                                                                        FFIND	
LBDADOS	0	CHAR	 13	00	00	00	30	00	  3	  2		  0	  0	  0		  0					  0	  0								Dados________		
LBNOMECOMPLETO	0	CHAR	 13	00	00	00	30	00	  5	  2		  0	  0	  0		  0					  0	  0								Nome_Completo		
GV_NAME_FUNC	C	CHAR	 45	80	00	80	30	00	  5	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBPRIMEIRONOME	0	CHAR	 13	00	00	00	30	00	  6	  2		  0	  0	  0		  0					  0	  0								Primeiro_Nome		
GV_PRIMEIRO_NOME	C	CHAR	 45	80	00	80	30	00	  6	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBSOBRENOME	0	CHAR	 13	00	00	00	30	00	  7	  2		  0	  0	  0		  0					  0	  0								Sobrenome____		
GV_SOBRENOME	C	CHAR	 45	80	00	80	30	00	  7	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBCIDADE	0	CHAR	 13	00	00	00	30	00	  8	  2		  0	  0	  0		  0					  0	  0								Cidade_______		
GV_CIDADE	C	CHAR	 45	80	00	80	30	00	  8	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBBAIRRO	0	CHAR	 13	00	00	00	30	00	  9	  2		  0	  0	  0		  0					  0	  0								Bairro_______		
GV_BAIRRO	C	CHAR	 45	80	00	80	30	00	  9	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBNASCIMENTO	0	CHAR	 13	00	00	00	30	00	 10	  2		  0	  0	  0		  0					  0	  0								Nascimento___		
GV_NASCIMENTO	D	DATS	 45	80	00	80	30	00	 10	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBMOD	0	CHAR	 13	00	00	00	30	00	 12	  2		  0	  0	  0		  0					  0	  0								Modificações_		
LBENDERECO	0	CHAR	 13	00	00	00	30	00	 14	  2		  0	  0	  0		  0					  0	  0								Endereço_____	                                                                                                                                                                                                                                                        X	
GWA_PA0006-STRAS	C	CHAR	 45	80	00	80	00	00	 14	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
LBSETBAIRRO	0	CHAR	 13	00	00	00	30	00	 15	  2		  0	  0	  0		  0					  0	  0								Bairro_______		
GWA_PA0006-ORT02	C	CHAR	 45	80	00	80	00	00	 15	 16		  0	  0	  0		  0					  0	  0								_____________________________________________		
BTNMOD		CHAR	 24	00	00	00	30	00	 17	 40		  0	  0	  0		 21	P				  0	  0	102							@0Z@_Modificar__________	                                                                                                                                                                        FEDIT	
LBRELATORIO	0	CHAR	 15	00	00	00	30	00	 19	  2		  0	  0	  0		  0					  0	  0								Relatorios_____		
LBBONUSRELA	0	CHAR	 15	00	00	00	30	00	 20	  2		  0	  0	  0		  0					  0	  0								Relatorio_Bonus		
BTNRELATORIO		CHAR	 23	00	00	00	30	00	 20	 40		  0	  0	  0		 21	P				  0	  0	103							@0E@_Gerar_____________	                                                                                                                                                                        FPRINT	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
  MODULE status_9013.																																
																																
PROCESS AFTER INPUT.																																
  MODULE user_command_9013.																																
%_PARAMS																																
																																
